"""New changes

Revision ID: 4f2a9400ea4e
Revises: e6bfcbd2daeb
Create Date: 2026-07-14 12:28:07.277197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2a9400ea4e'
down_revision: Union[str, Sequence[str], None] = 'e6bfcbd2daeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_posts_category_id'), 'posts', ['category_id'], unique=False)
    op.drop_constraint(op.f('posts_category_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('posts_tags_post_id_fkey'), 'posts_tags', type_='foreignkey')
    op.drop_constraint(op.f('posts_tags_tag_id_fkey'), 'posts_tags', type_='foreignkey')
    op.create_foreign_key(None, 'posts_tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'posts_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.create_foreign_key(op.f('posts_tags_tag_id_fkey'), 'posts_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('posts_tags_post_id_fkey'), 'posts_tags', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_category_id_fkey'), 'posts', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_posts_category_id'), table_name='posts')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
