"""New table: Comment | New columns in: Tag, Category, Post 

Revision ID: c62a235da8c9
Revises: c3039ffbc570
Create Date: 2026-07-12 18:45:03.906268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62a235da8c9'
down_revision: Union[str, Sequence[str], None] = 'c3039ffbc570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.add_column('categories', sa.Column('description', sa.String(), nullable=False))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('posts', sa.Column('description', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('views_count', sa.Integer(), nullable=False))
    op.add_column('tags', sa.Column('description', sa.String(), nullable=False))
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_column('tags', 'description')
    op.drop_column('posts', 'views_count')
    op.drop_column('posts', 'likes_count')
    op.drop_column('posts', 'description')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'description')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
